management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
      base-path: /actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted

spring:
  redis:
    host: localhost
    port: 6379