management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
      base-path: /actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cineAI
    username: sa
    password:
  jpa:
    show-sql: true # SQL 쿼리 로그 출력
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  http:
    multipart:
      enabled: true
      max-file-size: 5MB # 파일 크기 제한
      max-request-size: 5MB # 요청 크기 제한

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

file:
  dir: C:\workspace\cineAI\images\
  #dir: /app/data/images/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
